package com.cmput301.cs.project.model;

import android.os.Parcel;
import android.os.Parcelable;
import com.cmput301.cs.project.controllers.TagsManager;

import java.util.UUID;

public class Tag implements Comparable<Tag>, Parcelable {

    private final String mId;
    private final String mName;

    public Tag(String name, TagsManager manager) {
        this(name, manager, UUID.randomUUID().toString());
    }

    public Tag(String name, TagsManager manager, String id) {
        ClaimUtils.nonNullOrThrow(manager, "manager");
        mName = name.trim();
        mId = id;
    }

    public String getId() {
        return mId;
    }

    public String getName() {
        return this.mName;
    }

    @Override
    public int compareTo(Tag o) {
        return mName.compareTo(o.getName());
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Tag)) return false;

        final Tag tag = (Tag) o;

        if (!mId.equals(tag.mId)) return false;
        if (!mName.equals(tag.mName)) return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = mId.hashCode();
        result = 31 * result + mName.hashCode();
        return result;
    }

    // generated by http://www.parcelabler.com/
    protected Tag(Parcel in) {
        mId = in.readString();
        mName = in.readString();
    }

    @Override
    public int describeContents() {
        return 0;
    }

    // generated by http://www.parcelabler.com/
    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(mId);
        dest.writeString(mName);
    }

    // generated by http://www.parcelabler.com/
    @SuppressWarnings("unused")
    public static final Parcelable.Creator<Tag> CREATOR = new Parcelable.Creator<Tag>() {
        @Override
        public Tag createFromParcel(Parcel in) {
            return new Tag(in);
        }

        @Override
        public Tag[] newArray(int size) {
            return new Tag[size];
        }
    };
}