package com.cmput301.cs.project.models;

import android.os.Parcel;
import android.os.Parcelable;
import com.google.android.gms.maps.model.LatLng;

/**
 * Immutable class. Use {@link com.cmput301.cs.project.models.Destination.Builder Builder} to obtain an instance.
 */
public final class Destination implements Parcelable {

    /**
     * Use this class to obtain instances of {@code Destination}.
     * <p/>
     * Creating a Destination:
     * <pre>
     * final Destination des = new Destination.Builder()
     *      .reason(canBeNull)
     *      .name(nonNullString)
     *      .location(nonNullLatLng)
     *      .build();
     * </pre>
     * Editing a Destination:
     * <pre>
     * final Destination oldDes = …;
     * final Destination des = oldDes.edit()
     *      .reason(canBeNull)
     *      .name(nonNullString)
     *      .location(nonNullLatLng)
     *      .build();
     * </pre>
     */
    public static final class Builder {
        private String mName;
        private LatLng mLocation;
        private String mReason;

        public Builder() {
        }

        /**
         * Creates a new {@code Builder} with the specified parameters.
         *
         * @param name   non-null {@code String}
         * @param reason nullable {@code String}
         */
        public Builder(String name, String reason) {
            mName = ClaimUtils.nonNullNonEmptyOrThrow(name, "name");
            mReason = reason;
        }

        private Builder(Destination destination) {
            mName = destination.getName();
            mLocation = destination.getLocation();
            mReason = destination.getReason();
        }

        /**
         * @param name non-null {@code String}
         * @return this instance of {@code Builder}
         */
        public Builder name(String name) {
            mName = ClaimUtils.nonNullNonEmptyOrThrow(name, "name");
            return this;
        }

        /**
         * @param location non-null {@code LatLng}
         * @return this instance of {@code Builder}
         */
        public Builder location(LatLng location) {
            mLocation = ClaimUtils.nonNullOrThrow(location, "location");
            return this;
        }

        /**
         * @param reason nullable {@code String}
         * @return this instance of {@code Builder}
         */
        public Builder reason(String reason) {
            mReason = reason;
            return this;
        }

        public String getName() {
            return mName;
        }

        public LatLng getLocation() {
            return mLocation;
        }

        public String getReason() {
            return mReason;
        }

        public Destination build() {
            return new Destination(this);
        }
    }

    private final String mName;
    private final LatLng mLocation;
    private final String mReason;

    private Destination(Builder b) {
        mName = b.mName;
        mLocation = b.mLocation;
        mReason = b.mReason;
    }

    protected Destination(Parcel in) {
        mName = in.readString();
        mLocation = in.readParcelable(LatLng.class.getClassLoader());
        mReason = in.readString();
    }

    /**
     * @return a {@link Builder} with the values of this {@code Destination}
     */
    public Builder edit() {
        return new Builder(this);
    }

    /**
     * @return nullable {@code String} for name
     */
    public String getName() {
        return mName;
    }

    /**
     * @return nullable {@link LatLng} for location
     */
    public LatLng getLocation() {
        return mLocation;
    }

    /**
     * @return nullable {@code String} for reason
     */
    public String getReason() {
        return mReason;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    // generated by http://www.parcelabler.com/
    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(mName);
        dest.writeParcelable(mLocation, 0);
        dest.writeString(mReason);
    }

    // generated by http://www.parcelabler.com/
    public static final Parcelable.Creator<Destination> CREATOR = new Parcelable.Creator<Destination>() {
        @Override
        public Destination createFromParcel(Parcel in) {
            return new Destination(in);
        }

        @Override
        public Destination[] newArray(int size) {
            return new Destination[size];
        }
    };

    // Generated by IntelliJ
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Destination)) return false;

        final Destination that = (Destination) o;

        if (mName != null ? !mName.equals(that.mName) : that.mName != null) return false;
        if (mLocation != null ? !mLocation.equals(that.mLocation) : that.mLocation != null) return false;
        return !(mReason != null ? !mReason.equals(that.mReason) : that.mReason != null);

    }

    // Generated by IntelliJ
    @Override
    public int hashCode() {
        int result = mName != null ? mName.hashCode() : 0;
        result = 31 * result + (mLocation != null ? mLocation.hashCode() : 0);
        result = 31 * result + (mReason != null ? mReason.hashCode() : 0);
        return result;
    }
}