package com.cmput301.cs.project.models;


import android.net.Uri;
import android.os.Parcel;
import android.os.Parcelable;

import java.io.File;

/**
 * This class creates an instance that will hold the receipt image file for a particular expense.
 * If the image file exceeds the size limit of 65536 bytes, an exception error occurs.
 */

public class Receipt implements Parcelable {
    public static final int MAX_FILE_SIZE = 65536;

    private final File mFile;

    public Receipt(String path) {
        this(new File(path));
    }

    public Receipt(File file) {
        if (file.length() > MAX_FILE_SIZE) {
            throw new UnsupportedOperationException();

            //TODO: limit file size by compressing etc.
        }
        mFile = file;
    }

    public Uri getUri() {
        return Uri.fromFile(mFile);
    }

    public File getFile() {
        return mFile;
    }

    // generated by http://www.parcelabler.com/
    protected Receipt(Parcel in) {
        mFile = (File) in.readSerializable();
    }

    // generated by http://www.parcelabler.com/
    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeSerializable(mFile);
    }

    @Override
    public int describeContents() {
        return 0;
    }


    // generated by http://www.parcelabler.com/
    @SuppressWarnings("unused")
    public static final Parcelable.Creator<Receipt> CREATOR = new Parcelable.Creator<Receipt>() {
        @Override
        public Receipt createFromParcel(Parcel in) {
            return new Receipt(in);
        }

        @Override
        public Receipt[] newArray(int size) {
            return new Receipt[size];
        }
    };
}
