package com.cmput301.cs.project.models;

import android.os.Parcel;
import android.os.Parcelable;

import com.cmput301.cs.project.controllers.TagsManager;

import java.util.UUID;

/**
 * Class that contains a name and a unique ID that a user can associate with a {@link com.cmput301.cs.project.models.Claim Claim}. A {@link com.cmput301.cs.project.models.Claim Claim} can hold any number of tags that are associated with the claimant ({@link com.cmput301.cs.project.models.User User}) <p>
 * Specific tags are bound to a {@link com.cmput301.cs.project.models.User User} (device). <p>
 * <pre>
 * <b>Creating a new Tag:</b>  final Tag tag = new Tag(name, this);
 * 
 * 
 * <b>Editing an Existing Tag:</b>  final Tag newTag = new Tag(newName, this, oldTag.getId());
 * 
 * After creating renaming the old tag make sure to delete the oldTag from the list and adding the newTag to the list of tags <p>
 *</pre>
 *<p>
 *
 * The Parcelable implementation allows the tags to be passed into and pulled out of intents by using intent.putExtra() and intent.getExtra() respectively.
 * <p>
 * Each tag is given a random unique id upon construction.
 * @author rozsa
 * @author jbenson
 *
 */

public class Tag implements Comparable<Tag>, Parcelable {

    private final String mId;
    private final String mName;
    /**
     * generates a random ID for the tag using the randomUUID() method.
     * @param name
     * @param manager
     */
    public Tag(String name, TagsManager manager) {
        this(name, manager, UUID.randomUUID().toString());
    }

    public Tag(String name, TagsManager manager, String id) {
        ClaimUtils.nonNullOrThrow(manager, "manager");
        mName = name.trim();
        mId = ClaimUtils.nonNullOrThrow(id, "id");
    }

    public String getId() {
        return mId;
    }

    public String getName() {
        return this.mName;
    }

    @Override
    public int compareTo(Tag o) {
        return mName.compareTo(o.getName());
    }

    // Generated by IntelliJ
    @Override
    @SuppressWarnings("SimplifiableIfStatement")
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Tag)) return false;

        final Tag tag = (Tag) o;

        if (!mId.equals(tag.mId)) return false;
        return mName.equals(tag.mName);

    }

    // Generated by IntelliJ
    @Override
    public int hashCode() {
        int result = mId.hashCode();
        result = 31 * result + mName.hashCode();
        return result;
    }
    
    /**
     * this code is merely implementing Android.Parcelable<p>
     * you can read more on Parcels here: 
     * @param in
     */
    // generated by http://www.parcelabler.com/
    protected Tag(Parcel in) {
        mId = in.readString();
        mName = in.readString();
    }
    /**
     * this code is merely implementing Android.Parcelable<p>
     * 
     */
    @Override
    public int describeContents() {
        return 0;
    }
    
    /**
     * this code is merely implementing Android.Parcelable<p>
     */
    // generated by http://www.parcelabler.com/
    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(mId);
        dest.writeString(mName);
    }
    
    /**
     * this code is merely implementing Android.Parcelable<p>
     */
    // generated by http://www.parcelabler.com/
    @SuppressWarnings("unused")
    public static final Parcelable.Creator<Tag> CREATOR = new Parcelable.Creator<Tag>() {
        @Override
        public Tag createFromParcel(Parcel in) {
            return new Tag(in);
        }

        @Override
        public Tag[] newArray(int size) {
            return new Tag[size];
        }
    };
}