package com.cmput301.cs.project.models;

import android.os.Parcel;
import android.os.Parcelable;

import java.util.UUID;

/**
 * This class allows for the creation of and association of a username and user id to a user that will allow
 *  the user to log into the application and use it. <p>
 *  
 *  each user is assigned a unique ID on construction which is important when loading claims to know when user is a claimant and when they are an approver.<p>
 *  
 *  This class is used throughout most of the app because alot of items are tagged to their user. References can be found in:
 *  <ul>
 *  <li> {@link com.cmput301.cs.project.App App}
 *  	<ul>
 *  	<li> createUser()
 *  	<li> getUser()
 *  	</ul>
 *  <li> {@link com.cmput301.cs.project.activities.ClaimListActivity ClaimListActivity}
 *  	<ul>
 *  	<li> onCreate()
 *  	</ul>
 *  <li> {@link com.cmput301.cs.project.activities.LoginActivity LoginActivity}
 *  	<ul>
 *  	<li> login(View)
 *  	</ul>
 *  <li> {@link com.cmput301.cs.project.activities.ClaimListController ClaimListController}
 *  	<ul>
 *  	<li> ClaimListController(User, ClaimsList)
 *  	</ul>
 *  <li> {@link com.cmput301.cs.project.models.Claim Claim }
 *  	<ul>
 *  	<li> canApprover(User)
 *  	<li> getClaimant()
 *  	</ul>
 *  <li> {@link com.cmput301.cs.project.models.ClaimsList ClaimsList }
 *  <li> {@link com.cmput301.cs.project.models.Comment Comment }
 *  	<ul>
 *  	<li> Comment(String, User)
 *  	<li> getApprover()
 *  	</ul>
 *  <li> {@link com.cmput301.cs.project.models.Tag Tag }
 *  <li> {@link com.cmput301.cs.project.models.User User }
 *  </ul>
 */

public class User implements Parcelable, Saveable {

    private final String name;
    private final UUID userId;

    public User(String userName) {
        this(userName, UUID.randomUUID().toString());
    }

    public User(String userName, String userId) {
        if(userName == null || userName.isEmpty()) {
            throw new IllegalArgumentException();
        }

        this.name = userName;
        this.userId = UUID.fromString(userId);
    }

    public String getUserName() {
        return name;
    }

    public String getId() {
        return userId.toString();
    }

    // Generated by IntelliJ
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof User)) return false;

        final User user = (User) o;

        if (!name.equals(user.name)) return false;
        return userId.equals(user.userId);

    }

    // Generated by IntelliJ
    @Override
    public int hashCode() {
        int result = name.hashCode();
        result = 31 * result + userId.hashCode();
        return result;
    }

    // generated by http://www.parcelabler.com/
    /**
     * this code is merely implementing Android.Parcelable<p>
     * you can read more on Parcels here: <a href="http://developer.android.com/reference/android/os/Parcelable.html"> http://developer.android.com</a>
     */
    protected User(Parcel in) {
        name = in.readString();
        userId = (UUID) in.readValue(UUID.class.getClassLoader());
    }

    @Override
    public int describeContents() {
        return 0;
    }

    // generated by http://www.parcelabler.com/
    /**
     * this code is merely implementing Android.Parcelable<p>
     * you can read more on Parcels here: <a href="http://developer.android.com/reference/android/os/Parcelable.html"> http://developer.android.com</a>
     */
    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(name);
        dest.writeValue(userId);
    }

    // generated by http://www.parcelabler.com/
    /**
     * this code is merely implementing Android.Parcelable<p>
     * you can read more on Parcels here: <a href="http://developer.android.com/reference/android/os/Parcelable.html"> http://developer.android.com</a>
     */
    public static final Parcelable.Creator<User> CREATOR = new Parcelable.Creator<User>() {
        @Override
        public User createFromParcel(Parcel in) {
            return new User(in);
        }

        @Override
        public User[] newArray(int size) {
            return new User[size];
        }
    };
}